### ISSUE TITLE
Yii2 Object class compatibility error

### ISSUE THREAD

**Issue by strorch** [Vintage-web-production/yii2-invisible-recaptcha#2]
Hello!
I'm want to use this package to my project, but it has deprecated part in InvisibleRecaptchaValidator.

Here is my pr wich fix it.
https://github.com/Inspired-by-Boredom/yii2-invisible-recaptcha/pull/1

**Comment by greeflas** [comment]
@strorch Hi!
Thank you! Issue was fixed in 1.0.1 version.
